package com.tamapoke.core.dex

import com.tamapoke.core.enums.Rarity

/**
 * In-memory Pokedex, loaded once from dex.json (generated by tools/gen_dex_json.py
 * from the same tools/dex_data.py that produces the firmware's dex.h — single
 * source of truth for both).
 */
class DexTable(
    entries: List<DexEntry>,
    val eeveeId: Int,
    val eeveeEvolutions: List<Int>,
    val classicStarters: List<Int>,
) {
    private val byId: Map<Int, DexEntry> = entries.associateBy { it.id }

    val count: Int get() = byId.size

    operator fun get(id: Int): DexEntry =
        byId[id] ?: error("Unknown dex id $id")

    fun contains(id: Int): Boolean = byId.containsKey(id)

    fun entriesOfRarity(rarity: Rarity): List<DexEntry> =
        byId.values.filter { it.rarity == rarity }

    fun all(): Collection<DexEntry> = byId.values
}
