package com.tamapoke.app.data

import android.content.Context
import com.tamapoke.core.dex.DexEntry
import com.tamapoke.core.dex.DexTable
import com.tamapoke.core.enums.BattleType
import com.tamapoke.core.enums.Rarity
import org.json.JSONObject

private val LANGS = listOf("es", "en", "fr", "de", "it", "pt")

/**
 * Loads assets/dex.json (generated by tools/gen_dex_json.py from the same
 * tools/dex_data.py that produces the firmware's dex.h) into a [DexTable].
 */
object DexAssetLoader {
    fun load(context: Context): DexTable {
        val text = context.assets.open("dex.json").bufferedReader().use { it.readText() }
        val root = JSONObject(text)
        val speciesJson = root.getJSONArray("species")
        val entries = buildList {
            for (i in 0 until speciesJson.length()) {
                val o = speciesJson.getJSONObject(i)
                val baseStats = o.getJSONObject("baseStats")
                val namesJson = o.optJSONObject("names")
                val names = if (namesJson != null) {
                    LANGS.mapNotNull { lang -> namesJson.optString(lang, null)?.let { lang to it } }.toMap()
                } else {
                    emptyMap()
                }
                add(
                    DexEntry(
                        id = o.getInt("id"),
                        slug = o.getString("slug"),
                        name = o.getString("name"),
                        type = o.getString("type"),
                        accent = o.getString("accent"),
                        evolvesTo = o.getInt("evolvesTo"),
                        evolveLevel = o.getInt("evolveLevel"),
                        rarity = Rarity.valueOf(o.getString("rarity")),
                        baseHp = baseStats.getInt("hp"),
                        baseAtk = baseStats.getInt("atk"),
                        baseDef = baseStats.getInt("def"),
                        baseSpe = baseStats.getInt("spe"),
                        biome = o.getInt("biome"),
                        battleType1 = BattleType.fromSlug(o.optString("type1", null)),
                        battleType2 = BattleType.fromSlug(o.optString("type2", null)),
                        localizedNames = names,
                    ),
                )
            }
        }
        val eeveeEvolutions = root.getJSONArray("eeveeEvolutions").let { arr ->
            (0 until arr.length()).map { arr.getInt(it) }
        }
        val classicStarters = root.getJSONArray("classicStarters").let { arr ->
            (0 until arr.length()).map { arr.getInt(it) }
        }
        return DexTable(
            entries = entries,
            eeveeId = root.getInt("eeveeId"),
            eeveeEvolutions = eeveeEvolutions,
            classicStarters = classicStarters,
        )
    }
}
