#!/usr/bin/env python3
"""Genera res/values{,-xx}/strings_original.xml para Android desde i18n.h/i18n.cpp.

Convierte los especificadores printf (%s, %u, %d, %lu) al formato posicional
de Android (%1$s, %1$d, ...) y escapa el texto para XML. Es la unica fuente
de estas cadenas: no se editan a mano los strings_original.xml generados.

  python3 tools/gen_android_strings.py
"""
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(__file__), '..')
LANGS = ['es', 'en', 'fr', 'de', 'it', 'pt']  # orden del enum Lang en i18n.h


def read(path):
    with open(path, encoding='utf-8') as f:
        return f.read()


def parse_ids():
    h = read(os.path.join(ROOT, 'i18n.h'))
    block = re.search(r'enum StrId : uint8_t \{([\s\S]*?)\};', h).group(1)
    ids = []
    for line in block.splitlines():
        line = re.sub(r'//.*', '', line).strip()
        if not line:
            continue
        for tok in line.split(','):
            name = tok.strip()
            if name and name != 'STR_COUNT':
                ids.append(name)
    return ids


def parse_blocks():
    cpp = read(os.path.join(ROOT, 'i18n.cpp'))
    table = re.search(
        r'static const char \*const STRINGS\[LANG_COUNT\]\[STR_COUNT\] = \{([\s\S]*?)\n\};', cpp,
    ).group(1)
    parts = re.split(r'// -{4,} \w+ -{4,}', table)[1:]
    return parts


def extract_strings(block):
    return re.findall(r'"((?:[^"\\]|\\.)*)"', block)


def to_android_format(s):
    counter = {'n': 0}

    def repl(m):
        counter['n'] += 1
        spec = m.group(1)
        conv = 's' if spec == 's' else 'd'
        return f'%{counter["n"]}${conv}'

    return re.sub(r'%(lu|ld|u|d|s)', repl, s)


def xml_escape(s):
    return (
        s.replace('&', '&amp;')
        .replace('<', '&lt;')
        .replace('>', '&gt;')
        .replace("'", "\\'")
        .replace('"', '\\"')
    )


def key_for(str_id):
    return 'orig_' + str_id[2:].lower()  # strip "S_"


def main():
    ids = parse_ids()
    blocks = parse_blocks()
    for lang, block in zip(LANGS, blocks):
        strings = extract_strings(block)
        if len(strings) != len(ids):
            sys.exit(f'MISMATCH lang={lang} ids={len(ids)} strings={len(strings)}')
        dirname = 'values' if lang == 'en' else f'values-{lang}'
        out_dir = os.path.join(ROOT, 'android', 'app', 'src', 'main', 'res', dirname)
        os.makedirs(out_dir, exist_ok=True)

        lines = ['<?xml version="1.0" encoding="utf-8"?>', '<resources>',
                 '    <!-- GENERATED by tools/gen_android_strings.py from i18n.h/i18n.cpp - do not edit by hand -->']
        for str_id, value in zip(ids, strings):
            lines.append(f'    <string name="{key_for(str_id)}">{xml_escape(to_android_format(value))}</string>')
        lines.append('</resources>')

        out_path = os.path.join(out_dir, 'strings_original.xml')
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines) + '\n')
        print(f'guardado {os.path.normpath(out_path)} ({len(ids)} cadenas)')


if __name__ == '__main__':
    main()
